//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the cloud_to_grid package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __cloud_to_grid__CLOUD_TO_GRIDCONFIG_H__
#define __cloud_to_grid__CLOUD_TO_GRIDCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace cloud_to_grid
{
  class cloud_to_gridConfigStatics;

  class cloud_to_gridConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(cloud_to_gridConfig &config, const cloud_to_gridConfig &max, const cloud_to_gridConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const cloud_to_gridConfig &config1, const cloud_to_gridConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, cloud_to_gridConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const cloud_to_gridConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, cloud_to_gridConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const cloud_to_gridConfig &config) const = 0;
      virtual void getValue(const cloud_to_gridConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T cloud_to_gridConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T cloud_to_gridConfig::* field;

      virtual void clamp(cloud_to_gridConfig &config, const cloud_to_gridConfig &max, const cloud_to_gridConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const cloud_to_gridConfig &config1, const cloud_to_gridConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, cloud_to_gridConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const cloud_to_gridConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, cloud_to_gridConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const cloud_to_gridConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const cloud_to_gridConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, cloud_to_gridConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, cloud_to_gridConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<cloud_to_gridConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(cloud_to_gridConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("mode"==(*_i)->name){mode = boost::any_cast<bool>(val);}
        if("project_direction"==(*_i)->name){project_direction = boost::any_cast<int>(val);}
        if("searchRadius"==(*_i)->name){searchRadius = boost::any_cast<double>(val);}
        if("deviation"==(*_i)->name){deviation = boost::any_cast<double>(val);}
        if("sigma"==(*_i)->name){sigma = boost::any_cast<double>(val);}
        if("threshold"==(*_i)->name){threshold = boost::any_cast<int>(val);}
        if("cellResolution"==(*_i)->name){cellResolution = boost::any_cast<double>(val);}
        if("clip_max"==(*_i)->name){clip_max = boost::any_cast<double>(val);}
        if("clip_min"==(*_i)->name){clip_min = boost::any_cast<double>(val);}
        if("map_size"==(*_i)->name){map_size = boost::any_cast<double>(val);}
      }
    }

    bool mode;
int project_direction;
double searchRadius;
double deviation;
double sigma;
int threshold;
double cellResolution;
double clip_max;
double clip_min;
double map_size;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int project_direction;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double searchRadius;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double deviation;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int threshold;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cellResolution;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double clip_max;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double clip_min;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double map_size;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("cloud_to_gridConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const cloud_to_gridConfig &__max__ = __getMax__();
      const cloud_to_gridConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const cloud_to_gridConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const cloud_to_gridConfig &__getDefault__();
    static const cloud_to_gridConfig &__getMax__();
    static const cloud_to_gridConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const cloud_to_gridConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void cloud_to_gridConfig::ParamDescription<std::string>::clamp(cloud_to_gridConfig &config, const cloud_to_gridConfig &max, const cloud_to_gridConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class cloud_to_gridConfigStatics
  {
    friend class cloud_to_gridConfig;

    cloud_to_gridConfigStatics()
    {
cloud_to_gridConfig::GroupDescription<cloud_to_gridConfig::DEFAULT, cloud_to_gridConfig> Default("Default", "", 0, 0, true, &cloud_to_gridConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<bool>("mode", "bool", 0, "false:global,true:increasing", "", &cloud_to_gridConfig::mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<bool>("mode", "bool", 0, "false:global,true:increasing", "", &cloud_to_gridConfig::mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.project_direction = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.project_direction = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.project_direction = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<int>("project_direction", "int", 0, "project_direction x-y or y-z or x-z", "{'enum': [{'name': 'x', 'type': 'int', 'value': 0, 'srcline': 9, 'srcfile': '/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg', 'description': 'projection to y-z', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'y', 'type': 'int', 'value': 1, 'srcline': 10, 'srcfile': '/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg', 'description': 'projection to z-x', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'z', 'type': 'int', 'value': 2, 'srcline': 11, 'srcfile': '/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg', 'description': 'projection to x-y', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'project_direction'}", &cloud_to_gridConfig::project_direction)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<int>("project_direction", "int", 0, "project_direction x-y or y-z or x-z", "{'enum': [{'name': 'x', 'type': 'int', 'value': 0, 'srcline': 9, 'srcfile': '/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg', 'description': 'projection to y-z', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'y', 'type': 'int', 'value': 1, 'srcline': 10, 'srcfile': '/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg', 'description': 'projection to z-x', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'z', 'type': 'int', 'value': 2, 'srcline': 11, 'srcfile': '/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg', 'description': 'projection to x-y', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'project_direction'}", &cloud_to_gridConfig::project_direction)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.searchRadius = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.searchRadius = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.searchRadius = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("searchRadius", "double", 0, "pcl cloud searchRadius", "", &cloud_to_gridConfig::searchRadius)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("searchRadius", "double", 0, "pcl cloud searchRadius", "", &cloud_to_gridConfig::searchRadius)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.deviation = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.deviation = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.deviation = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("deviation", "double", 0, "a threshold to decide whether a point is obstacal", "", &cloud_to_gridConfig::deviation)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("deviation", "double", 0, "a threshold to decide whether a point is obstacal", "", &cloud_to_gridConfig::deviation)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("sigma", "double", 0, "balance between height and normal vector", "", &cloud_to_gridConfig::sigma)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("sigma", "double", 0, "balance between height and normal vector", "", &cloud_to_gridConfig::sigma)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.threshold = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.threshold = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.threshold = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<int>("threshold", "int", 0, "behind this value,the grid is considered occupied", "", &cloud_to_gridConfig::threshold)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<int>("threshold", "int", 0, "behind this value,the grid is considered occupied", "", &cloud_to_gridConfig::threshold)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cellResolution = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cellResolution = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cellResolution = 0.05;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("cellResolution", "double", 0, "map cellResolution", "", &cloud_to_gridConfig::cellResolution)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("cellResolution", "double", 0, "map cellResolution", "", &cloud_to_gridConfig::cellResolution)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.clip_max = -100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.clip_max = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.clip_max = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("clip_max", "double", 0, "max height to reserve", "", &cloud_to_gridConfig::clip_max)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("clip_max", "double", 0, "max height to reserve", "", &cloud_to_gridConfig::clip_max)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.clip_min = -100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.clip_min = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.clip_min = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("clip_min", "double", 0, "min height to reserve", "", &cloud_to_gridConfig::clip_min)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("clip_min", "double", 0, "min height to reserve", "", &cloud_to_gridConfig::clip_min)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.map_size = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.map_size = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.map_size = 40.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("map_size", "double", 0, "map size", "", &cloud_to_gridConfig::map_size)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(cloud_to_gridConfig::AbstractParamDescriptionConstPtr(new cloud_to_gridConfig::ParamDescription<double>("map_size", "double", 0, "map size", "", &cloud_to_gridConfig::map_size)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(cloud_to_gridConfig::AbstractGroupDescriptionConstPtr(new cloud_to_gridConfig::GroupDescription<cloud_to_gridConfig::DEFAULT, cloud_to_gridConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<cloud_to_gridConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<cloud_to_gridConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<cloud_to_gridConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    cloud_to_gridConfig __max__;
    cloud_to_gridConfig __min__;
    cloud_to_gridConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const cloud_to_gridConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static cloud_to_gridConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &cloud_to_gridConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const cloud_to_gridConfig &cloud_to_gridConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const cloud_to_gridConfig &cloud_to_gridConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const cloud_to_gridConfig &cloud_to_gridConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<cloud_to_gridConfig::AbstractParamDescriptionConstPtr> &cloud_to_gridConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<cloud_to_gridConfig::AbstractGroupDescriptionConstPtr> &cloud_to_gridConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const cloud_to_gridConfigStatics *cloud_to_gridConfig::__get_statics__()
  {
    const static cloud_to_gridConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = cloud_to_gridConfigStatics::get_instance();

    return statics;
  }

//#line 9 "/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg"
      const int cloud_to_grid_x = 0;
//#line 10 "/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg"
      const int cloud_to_grid_y = 1;
//#line 11 "/home/wang/bishe/slam/catkin_ws/src/cloud_to_grid/config/cloud_to_grid.cfg"
      const int cloud_to_grid_z = 2;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CLOUD_TO_GRIDRECONFIGURATOR_H__
